---
- name: Instalar WebServer na Ec2 com Ubuntu
  hosts: tag_Webserver_true
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "~/access_keys/lazevedo-elvenworks.pem"
  become: yes

  roles:
    - common
    - webserver

