---
  - name: Criar Alias para o python
    shell: alias python=python3

  - name: Install basic packages
    apt:
      name: "{{ packages }}"
      state: latest
      update_cache: yes
    ignore_errors:  true

  - name: Download Wordpress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: "{{ wp_path }}"
      remote_src: yes
      creates: "{{ wp_path }}/wordpress"

  - name: Definir proprietário
    file:
      path: "{{ wp_path }}"
      state: directory
      recurse: yes
      owner: www-data
      group: www-data

  - name: Configurar permissão para as pastas
    shell: "/usr/bin/find /usr/share/nginx/wordpress/ -type d -exec chmod 750 {} \\;"

  - name: Configurar permissão para os arquivos
    shell: "/usr/bin/find /usr/share/nginx/wordpress/ -type f -exec chmod 640 {} \\;"

  - name: Cria database no RDS
    mysql_db:
      login_user: administrator
      login_password: "{{ lookup('env','RDS_PASS') }}"
      login_host: "{{ lookup('env','RDS_HOST') }}"
      name: wordpress
      state: present

  - name: Cria o usuário no RDS
    mysql_user:
      login_user: administrator
      login_password: "{{ lookup('env','RDS_PASS') }}"
      login_host: "{{ lookup('env','RDS_HOST') }}"
      name: admin
      host: "%"
      password: 123Mudar
      priv: 'wordpress.*:ALL,GRANT'
      state: present

  - name: Copia arquivo de configuração WP
    copy:
      dest: "{{ wp_path }}/wordpress/"
      group: www-data
      owner: www-data
      mode: "0644"
      src: files/wp-config.php

  - name: Configura o Nginx para o Wordpress
    copy:
      dest: "/etc/nginx/conf.d/"
      group: root
      owner: root
      mode: "0644"
      src: files/meusite.com.conf
    notify:
      - Restart Nginx
      - Restart Php
